name: advicer
description: A new Flutter project showcasing a good clean architecture.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  bloc: ^7.2.1
  build_runner: ^2.1.7
  cupertino_icons: ^1.0.4
  dartz: ^0.10.1
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.0
  get_it: ^7.2.0
  
  http: ^0.13.4
  mockito: ^5.0.17
  provider: ^6.0.2
  shared_preferences: ^2.0.13

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
 